### ISSUE TITLE
If the center param is not valid, the node service crashes

### ISSUE THREAD

**Issue by amarinelli** [esri-es/Static-Map-Service-ArcGIS#1]
**Example:** [http://localhost:9095/?center=alsjdhlfgs](http://localhost:9095/?center=alsjdhlfgs)

Using the above URL stops the node.js service, closing the active cmd window where the service is being run.

**Comment by hhkaos** [comment]
Thanks Adam for noticing and so sorry for taking so long to fix it, I didn't see the issue ^_^''

Cheers
